version: '3.9'
services:
  web:
    build:
      dockerfile: Dockerfile-web
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: e2e
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'
    command: ['./wait-for-it.sh', 'postgres:5432', '--', 'npm', 'run', 'docker']
  postgres:
    image: postgres
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  e2e:
    build:
      dockerfile: Dockerfile-e2e
    environment:
      NODE_ENV: e2e
      E2E_URL: http://web:3000/#/
    depends_on:
      - 'web'
    command:
      [
        './wait-for-it.sh',
        'web:3000',
        '-t',
        '60',
        '--',
        'npm',
        'run',
        'docker:e2e'
      ]
