version: '3.9'
services:
  web:
    build: .
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: e2e
      PORT: 3000
    ports:
      - '3000:3000'
  postgres:
    image: postgres
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
