name: Linting and Testing
on:
  pull_request:
    branches:
    - dev
  
  push:
    branches:
    - dev
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Clean install of code
        run: npm ci
      - name: Linting
        run: npm run lint
      - run: echo ":green_apple: This job's status is ${{ job.status }}."
  Unit_Tests: 
    needs: Linting
    runs-on: ubuntu-latest
    steps:   
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Clean install of code
        run: npm ci
      - name: Unit Tests
        run: npm test
      - run: echo ":green_apple: This job's status is ${{ job.status }}."