name: CI/CD

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

env:
  JWT_SECRET: ${{secrets.JWT}}
  SENDGRID_API_KEY: ${{secrets.SENDGRID}}
  PORT: 3000
  # DEBUG: nock.*
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - name: Cache packages
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependencies
        run: npm ci
        
      - name: Linting
        run: "npm run lint -- --rule 'no-console: 2'"
        
      - name: Test
        run: npm run test
        
      ### the below is for E2E testing ###
      # - name: Build
      #   run: npm run build
        
      # - name: Seed data
      #   run: npm run db:seed

      # - name: Start test server
      #   run: npm run start & npx wait-on http://localhost:${{ env.PORT }}
        
      # - name: Skipping E2E Tests!
      #   run: npm run test:e2e
      
      ### the below is for deployment to Heroku ###
  # deploy:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  if: github.ref == 'refs/heads/dev'
  #  steps:
  #   - uses: actions/checkout@v2
     
  #   # - name: Add remote origin
  #   #   run: "git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/gardenz-app.git"

  #   - uses: akhileshns/heroku-deploy@master
  #     with:
  #       heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #       heroku_app_name: "gardenz-app"
  #       heroku_email: "ryan.julian.bosher@icloud.com"
  #       branch: ${{ env.TARGET_BRANCH_CD }}
  #   # - name: Deploy to Heroku
  #   #   run: git push heroku dev:refs/heads/main -f
  #     env:
  #       HD_SENDGRID_API_KEY: ${{secrets.SENDGRID}} 
