name: CI/CD

on:
  push:
    # branches: [ main, dev]
    branches: [ e2e-devops-integration ]
  pull_request:
    # branches: [ main, dev ]
    branches: [ e2e-devops-integration ]

env:
  JWT_SECRET: ${{secrets.JWT}}
  SENDGRID_API_KEY: ${{secrets.SENDGRID}}
  HEADLESS: true
  PORT: 3000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Cache packages
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Playwright for testing
        uses: microsoft/playwright-github-action@v1

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start test server
        run: npm run start & npx wait-on http://localhost:${{ PORT }}

      - name: Test
        run: npm run test

      - name: E2E Test
        run: npm run test:e2e
