# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD Deploy TEST

on:
  push:
    branches: [ e2e-devops-integration ]
  pull_request:
    branches: [ e2e-devops-integration ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2

     - uses: akhileshns/heroku-deploy@master
       with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_app_name: "bosh-gardenz-test"
         heroku_email: "ryan.julian.bosher@icloud.com"
         branch: "e2e-devops-integration"
       env:
        HD_JWT_SECRET: ${{secrets.JWT}}
        HD_SENDGRID_API_KEY: ${{secrets.SENDGRID}}
