name: Heroku Deploy

on:
  workflow_run:
    workflows: [ "Node.js CI" ]
    branches: [ main ]
    types:
      - completed

jobs:

  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: gardenz-app
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
