name: E2E

on:
  push:
    branches:
      - actionE2E
  pull_request:
    branches:
      - actionE2E

jobs:

  E2E:
    runs-on: ubuntu-latest
    environment: testing
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
      # with:
      #   node-version: ${{ matrix.node-version }}
    # - run: npm ci
    # - run: npm run build --if-present
    - run: npm run test:e2e
    runs:
    using: 'docker'
    image: 'Dockerfile'
