name: Push Container to Heroku

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pohutukawa-gardenz/heroku-deploy@v7.43
      with:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "pohutukawa-gardenz" 

