name: Deploy

on: 
  push:
   branches:
     -master

jobs:
  deploy-app:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pohutukawa-gardenz" #Must be unique in Heroku
          heroku_email: "bhivxx@gmail.com"
