name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      with:
        jestArgs: path/to/dummy.test.js
